// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	error1 "github.com/kappac/ve-back-end-utils/pkg/proto/error"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VEValidateTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VEValidateTokenRequest) Reset()         { *m = VEValidateTokenRequest{} }
func (m *VEValidateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*VEValidateTokenRequest) ProtoMessage()    {}
func (*VEValidateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *VEValidateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VEValidateTokenRequest.Unmarshal(m, b)
}
func (m *VEValidateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VEValidateTokenRequest.Marshal(b, m, deterministic)
}
func (m *VEValidateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VEValidateTokenRequest.Merge(m, src)
}
func (m *VEValidateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_VEValidateTokenRequest.Size(m)
}
func (m *VEValidateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VEValidateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VEValidateTokenRequest proto.InternalMessageInfo

func (m *VEValidateTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VEValidateTokenResponse struct {
	Info                 *VEProviderInfo         `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Request              *VEValidateTokenRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Error                *error1.VEError         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *VEValidateTokenResponse) Reset()         { *m = VEValidateTokenResponse{} }
func (m *VEValidateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*VEValidateTokenResponse) ProtoMessage()    {}
func (*VEValidateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *VEValidateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VEValidateTokenResponse.Unmarshal(m, b)
}
func (m *VEValidateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VEValidateTokenResponse.Marshal(b, m, deterministic)
}
func (m *VEValidateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VEValidateTokenResponse.Merge(m, src)
}
func (m *VEValidateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_VEValidateTokenResponse.Size(m)
}
func (m *VEValidateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VEValidateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VEValidateTokenResponse proto.InternalMessageInfo

func (m *VEValidateTokenResponse) GetInfo() *VEProviderInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *VEValidateTokenResponse) GetRequest() *VEValidateTokenRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *VEValidateTokenResponse) GetError() *error1.VEError {
	if m != nil {
		return m.Error
	}
	return nil
}

type VEProviderInfo struct {
	FullName             string   `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	GivenName            string   `protobuf:"bytes,2,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName           string   `protobuf:"bytes,3,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Picture              string   `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VEProviderInfo) Reset()         { *m = VEProviderInfo{} }
func (m *VEProviderInfo) String() string { return proto.CompactTextString(m) }
func (*VEProviderInfo) ProtoMessage()    {}
func (*VEProviderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *VEProviderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VEProviderInfo.Unmarshal(m, b)
}
func (m *VEProviderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VEProviderInfo.Marshal(b, m, deterministic)
}
func (m *VEProviderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VEProviderInfo.Merge(m, src)
}
func (m *VEProviderInfo) XXX_Size() int {
	return xxx_messageInfo_VEProviderInfo.Size(m)
}
func (m *VEProviderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VEProviderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VEProviderInfo proto.InternalMessageInfo

func (m *VEProviderInfo) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *VEProviderInfo) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *VEProviderInfo) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *VEProviderInfo) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *VEProviderInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*VEValidateTokenRequest)(nil), "pb.VEValidateTokenRequest")
	proto.RegisterType((*VEValidateTokenResponse)(nil), "pb.VEValidateTokenResponse")
	proto.RegisterType((*VEProviderInfo)(nil), "pb.VEProviderInfo")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcf, 0x6a, 0xe3, 0x30,
	0x10, 0xc6, 0xc9, 0xbf, 0xcd, 0x66, 0x42, 0x72, 0x10, 0xcb, 0xae, 0x49, 0x58, 0x76, 0x09, 0xa5,
	0xf4, 0x12, 0x1b, 0xd2, 0xbe, 0x40, 0x29, 0xa6, 0xed, 0xa5, 0x14, 0xb7, 0xf8, 0x5a, 0x64, 0x7b,
	0xec, 0x08, 0xdb, 0x92, 0x2a, 0xcb, 0x86, 0x3e, 0x4c, 0xdf, 0xb5, 0x78, 0xd4, 0x1c, 0x42, 0x43,
	0x4f, 0xe6, 0x9b, 0xdf, 0x7c, 0xd6, 0xcc, 0x37, 0xb0, 0x68, 0xd0, 0x74, 0x22, 0x45, 0x5f, 0x1b,
	0x65, 0x15, 0x1b, 0xea, 0x64, 0x75, 0x53, 0x08, 0xbb, 0x6f, 0x13, 0x3f, 0x55, 0x75, 0x50, 0x72,
	0xad, 0x79, 0x1a, 0x74, 0xb8, 0x4d, 0x78, 0x5a, 0x6e, 0x51, 0x66, 0xdb, 0xd6, 0x8a, 0xaa, 0x09,
	0x74, 0x59, 0x04, 0x64, 0x09, 0xd0, 0x18, 0x65, 0x82, 0x02, 0x25, 0x1a, 0x6e, 0x31, 0x73, 0x3f,
	0xda, 0xf8, 0xf0, 0x3b, 0x0e, 0x63, 0x5e, 0x89, 0x8c, 0x5b, 0x7c, 0x56, 0x25, 0xca, 0x08, 0x5f,
	0x5b, 0x6c, 0x2c, 0xfb, 0x05, 0x13, 0xdb, 0x6b, 0x6f, 0xf0, 0x7f, 0x70, 0x31, 0x8b, 0x9c, 0xd8,
	0xbc, 0x0f, 0xe0, 0xcf, 0x17, 0x43, 0xa3, 0x95, 0x6c, 0x90, 0x9d, 0xc3, 0x58, 0xc8, 0x5c, 0x91,
	0x61, 0xbe, 0x63, 0xbe, 0x4e, 0xfc, 0x38, 0x7c, 0x34, 0xaa, 0x13, 0x19, 0x9a, 0x7b, 0x99, 0xab,
	0x88, 0x38, 0xbb, 0x82, 0xa9, 0x71, 0x8f, 0x78, 0x43, 0x6a, 0x5d, 0xb9, 0xd6, 0x53, 0x63, 0x44,
	0x87, 0x56, 0x76, 0x06, 0x13, 0x5a, 0xc1, 0x1b, 0x91, 0x67, 0xe9, 0x93, 0xf2, 0xe3, 0x30, 0xec,
	0xbf, 0x91, 0x83, 0xfd, 0x7c, 0xcb, 0xe3, 0x47, 0xd9, 0x1a, 0x66, 0x79, 0x5b, 0x55, 0x2f, 0x92,
	0xd7, 0xf8, 0xb9, 0xcc, 0xcf, 0xbe, 0xf0, 0xc0, 0x6b, 0x64, 0x7f, 0x01, 0x0a, 0xd1, 0xa1, 0x74,
	0x74, 0x48, 0x74, 0x46, 0x15, 0xc2, 0xff, 0x60, 0x9e, 0xf3, 0x5a, 0x54, 0x6f, 0x8e, 0x8f, 0x88,
	0x83, 0x2b, 0x51, 0x83, 0x07, 0x53, 0x2d, 0x52, 0xdb, 0x1a, 0xf4, 0xc6, 0x04, 0x0f, 0xb2, 0xcf,
	0x0f, 0x6b, 0x2e, 0x2a, 0x6f, 0xe2, 0xf2, 0x23, 0xb1, 0x2b, 0x60, 0x1d, 0x87, 0xd7, 0xad, 0xdd,
	0x1f, 0x46, 0xbc, 0x55, 0xaa, 0xa8, 0xf0, 0xc9, 0x5d, 0x97, 0xdd, 0xc1, 0xe2, 0x28, 0x05, 0xf6,
	0x4d, 0x34, 0xab, 0xf5, 0x49, 0xe6, 0x8e, 0x91, 0xfc, 0xa0, 0xfb, 0x5e, 0x7e, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xb3, 0xe6, 0x51, 0xc9, 0x39, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VEAuthProviderGoogleServiceClient is the client API for VEAuthProviderGoogleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VEAuthProviderGoogleServiceClient interface {
	ValidateToken(ctx context.Context, in *VEValidateTokenRequest, opts ...grpc.CallOption) (*VEValidateTokenResponse, error)
}

type vEAuthProviderGoogleServiceClient struct {
	cc *grpc.ClientConn
}

func NewVEAuthProviderGoogleServiceClient(cc *grpc.ClientConn) VEAuthProviderGoogleServiceClient {
	return &vEAuthProviderGoogleServiceClient{cc}
}

func (c *vEAuthProviderGoogleServiceClient) ValidateToken(ctx context.Context, in *VEValidateTokenRequest, opts ...grpc.CallOption) (*VEValidateTokenResponse, error) {
	out := new(VEValidateTokenResponse)
	err := c.cc.Invoke(ctx, "/pb.VEAuthProviderGoogleService/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VEAuthProviderGoogleServiceServer is the server API for VEAuthProviderGoogleService service.
type VEAuthProviderGoogleServiceServer interface {
	ValidateToken(context.Context, *VEValidateTokenRequest) (*VEValidateTokenResponse, error)
}

func RegisterVEAuthProviderGoogleServiceServer(s *grpc.Server, srv VEAuthProviderGoogleServiceServer) {
	s.RegisterService(&_VEAuthProviderGoogleService_serviceDesc, srv)
}

func _VEAuthProviderGoogleService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VEValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VEAuthProviderGoogleServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VEAuthProviderGoogleService/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VEAuthProviderGoogleServiceServer).ValidateToken(ctx, req.(*VEValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VEAuthProviderGoogleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VEAuthProviderGoogleService",
	HandlerType: (*VEAuthProviderGoogleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _VEAuthProviderGoogleService_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
